# Generated by Django 4.2.5 on 2023-09-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='socio',
            name='dni',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='socio',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
