# Generated by Django 4.2.7 on 2023-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0002_socio_apellido_socio_dni_socio_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
