# Generated by Django 4.2.7 on 2023-11-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0004_socio_es_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='es_director',
        ),
    ]
