# Generated by Django 4.2.5 on 2023-10-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensualidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='costo_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
