# Generated by Django 4.2.5 on 2023-11-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensualidad', '0002_mensualidad_costo_a_pagar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensualidad',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='mes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
