# Generated by Django 4.2.7 on 2023-11-11 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensualidad', '0003_remove_mensualidad_fecha_vencimiento_mensualidad_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mensualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='mensualidad.mensualidad')),
            ],
        ),
    ]
