# Generated by Django 4.2.7 on 2023-11-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensualidad', '0004_fechamensualidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensualidad',
            name='costo_a_pagar',
        ),
        migrations.DeleteModel(
            name='FechaMensualidad',
        ),
    ]
