# Generated by Django 4.2.5 on 2023-11-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensualidad', '0004_alter_mensualidad_mesa_alter_mensualidad_socio'),
        ('mensualidad', '0006_mensualidad_costo_a_pagar'),
    ]

    operations = [
    ]
