# Generated by Django 4.2.5 on 2023-09-12 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='descripcion')),
                ('sistema', models.CharField(max_length=50)),
                ('rol_usuario', models.CharField(choices=[('jugador', 'Jugador'), ('director', 'Director')], max_length=10)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_dirigidas', to='socio.socio')),
                ('jugadores', models.ManyToManyField(related_name='mesas_jugadas', to='socio.socio')),
            ],
        ),
    ]
