# Generated by Django 4.2.5 on 2023-09-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0002_alter_mesa_jugadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='rol_usuario',
        ),
    ]
