# Generated by Django 4.2.5 on 2023-10-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0004_mesa_costo_mesa_regularidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='costo_director',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
